### ISSUE TITLE
Add an option like: --I-understand-dns-manual-mode , to force the user understand dns manual mode before using it.

### ISSUE THREAD

**Issue by Neilpang** [Neilpang/acme.sh#1029]
So many users are using  dns manual mode, but they don't really understand the manual mode .

I'd like to add a new command parameter, something like:
```sh
acme.sh  --issue -d example.com  --dns   --yes-I-understand-dns-manual-mode
```

Which forces the user to read our wiki and make sure they know they will need to manually renew the cert in 90 days.

Without given this new parameter,  acme.sh will show the wiki link and refuse to work.

**Comment by FernandoMiguel** [comment]
i though about this the other day.
i was going to propose that it would only work in --test mode, but there is at least one use case where it is useful:
when there is no cert and you want to do the initial cert via DNS.

if you go with that flag, i would suggest that the cron is also removed/commented out (if there arent more domains being issued)

**Comment by Neilpang** [comment]
@FernandoMiguel 
This flag will be only for the first initial issue of the domain.   
And the cron will work as before, that is showing a dns manual error message.

If the user confirms to `understand the dns manul mode` for the first time.  I would  assume he would take care of the certs by himself.

**Comment by comfytoday** [comment]
I have a question related to this, probably due to a misunderstanding about what dns manual mode, and auto dns mode actually do.

Initially I setup a certificate using manual mode, then when I went to test renewal I found that renewals were not supported in that mode. 

Is this because the DNS TXT entry would be required to change during the renewal? It's not totally clear from the wiki/doco. I'm not clear on why the entry would need to change, given it appears to be a securely communicated, random token.

Anyway, I setup aws cli and used --dns dns_aws to issue a cert. I deleted the first folder, and started from scratch. I also deleted the TXT records, expecting aws cli to add new ones itself. But when I issued the new cert, it said my domain was already verified, and skipped the auth process...

Now, when I try and do a test run to see if renewal will work, it spits this out:

`acme.sh --renew -d *.example.com --force`

> Single domain='*.example.com'
> Getting domain auth token for each domain
> Getting webroot for domain='*.example.com'
> *.example.com is already verified, skip dns-01.

This is confusing, because it appears that renewal using the manual mode would in fact work, becase it doesn't go through the auth process again. In fact, it doesn't appear to even check if the TXT records are still there

What am I missing here? How can I check if --dns aws_dns will/is actually working?

**Comment by FernandoMiguel** [comment]
The verification is valid for 30 days

--
Fernando Miguel

**Comment by comfytoday** [comment]
Just to be clear, at that point will it add a new TXT entry?

**Comment by Neilpang** [comment]
@comfytoday   yes, everytime, you need to add a new txt entry by your hand.

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/dns-manual-mode

```sh
acme.sh --issue -d example.com  -dns   \
   --yes-I-know-dns-manual-mode-enough-go-ahead-please
```

**Comment by FernandoMiguel** [comment]
ahahahahahah

**Comment by MAGICCC** [comment]
Well using the manual mode you need to add the TXT records by yourself, but acme.sh will still autorenew after x days. So you will end up having no TXT records in your DNS but acme.sh tries to renew your cert and will fail!
This command just ensures that the users will add them manually on their own every time acme.sh tries to renew the cert. 
And as stated in the wiki, its p. senseless in a production enviroment to use the manual mode

**Comment by tymik** [comment]
maybe it would be just clearer if the switch was saying --i-know-i-need-to-update-txt-record ? is self explanatory, doesn't bring any additional confusion - just my thoughts

**Comment by MAGICCC** [comment]
Oh yes maybe that makes more sense maybe so you know what to do while entering the parameter

**Comment by spiralw** [comment]
Hi! I got here from the warning in the wiki. I host my own DNS server which doesn't have an API (and I don't want to use an alias), so I need to use manual mode.

> using the manual mode you need to add the TXT records by yourself, but acme.sh will still autorenew after x days. So you will end up having no TXT records in your DNS but acme.sh tries to renew your cert and will fail!

I'm very confused by this. Why would there be no TXT records in my DNS? Would keeping the same DNS records *also* fail renewal? 

The wiki article is unclear on how to actually use manual mode. This issue, linked in the wiki, is also unclear. It's quite frustrating :/

**Comment by tymik** [comment]
> Hi! I got here from the warning in the wiki. I host my own DNS server which doesn't have an API (and I don't want to use an alias), so I need to use manual mode.
> 
> > using the manual mode you need to add the TXT records by yourself, but acme.sh will still autorenew after x days. So you will end up having no TXT records in your DNS but acme.sh tries to renew your cert and will fail!
> 
> I'm very confused by this. Why would there be no TXT records in my DNS? Would keeping the same DNS records _also_ fail renewal?
> 
> The wiki article is unclear on how to actually use manual mode. This issue, linked in the wiki, is also unclear. It's quite frustrating :/

@spiralw without the API you need to manually update TXT records for every renewal - shortly, you won't have them updated for new renewal, if you cannot put them there via API (or any sort of scripting if you host your own DNS server).

**Comment by rogeriojlle** [comment]
I suggest that this way, "acme.sh" saves the content for the txt record in a separate file, this would make it easier to use in other scripts.
