### ISSUE TITLE
[documentation] env variables

### ISSUE THREAD

**Issue by swirly** [Neilpang/acme.sh#1071]
Hello

I'm into creating a debian package for acme.sh. In order to do this, I'm looking for information on the various environnement variables in order to follow the FHS (file hierarchy standard). That is, I want to 

- put acme.sh live in /usr/sbin 
- put the deploy API in /usr/lib/acme/
- put all certificates in /var/acme/
- and all configuration in /etc/acme
- default conf in /etc/default/acme

Mos of this should certainly be done by using the correct env variables

Why don't I just use the actual installer ? Because I'm into serving almost 300 servers remotly and in an automated way. The debian infrastructure is already done for those servers, and having a clean debian installer would make the job easy.

Of course, all I will do shall not break existing configuration and will have a pull request

So, can you help me with the various env variables, and the way acme.sh look at them (I know, it's all in the sources, but they're quite long :))

TIA

**Comment by Neilpang** [comment]
1.   you can put acme.sh in any folder,   it doesn't care where it is.
2.  The most important env is  `LE_WORKING_DIR`. Its default value is `~/.acme.sh/`,  which should be a writable folder.  `acme.sh` will write/save any files/logs/certs etc in this folder by default.   You can either use env `LE_WORKING_DIR` or  use `--home` parameter.  they are equal.  for example:
```sh
export LE_WORKING_DIR=/usr/lib/acme/
acme.sh --issue ......
```
or:
```:
acme.sh  --home /usr/lib/acme/  --issue .......
```
However, it's more recommended to use commandline parameter instead of env.
Also, the `deploy` or `dnsapi` hooks  will also be searched from within `LE_WORKING_DIR` folder.
3. Second important env is `LE_CONFIG_HOME`,  it's very similar to `LE_WORKING_DIR`.  Its default is equal to `LE_WORKING_DIR`.    If you specify a value to `LE_CONFIG_HOME`,  any files/certs/logs will be saved in `LE_CONFIG_HOME`.    The only difference to `LE_WORKING_DIR` is that: the `deploy` or `dnsapi` hooks is never searched in `LE_CONFIG_HOME`.   It's just a dir to save `config`s.
There is also a commandline parameter for it: `--config-home`.
```sh
export LE_CONFIG_HOME=/etc/acme
acme.sh --issue ....
```
or
```sh
acme.sh --config-home /etc/acme  --issue ....
```
4. All the certs/keys are saved in `LE_CONFIG_HOME` by default, however, you can also specify `CERT_HOME`
```sh
export CERT_HOME= /var/acme/
```
or
```sh
acme.sh --cert-home   /var/acme/   --issue ....
```

**Comment by swirly** [comment]
Thank you for those precision. I'm looking at the source code and may be I'll propose some pukk request for creating a debian package directory and also some slight modification for configuration storage

LE_CONFIG_HOME seems to be something else than storing config ? It's made for logs/cert/files if I understant what you wrote. These are the config issued by the script, not the script configuration.

**Comment by aicioara** [comment]
This should be in the docs. Really helpful, thank you @Neilpang
