### ISSUE TITLE
使用dns的方式，多个域名前的流程一切正常，最后却只生成了一个域名的证书,

### ISSUE THREAD

**Issue by henjue** [Neilpang/acme.sh#1207]
```bash
#!/usr/bin/env sh
export DP_Id="xxxx"
export DP_Key="xxxxxx"
./acme.sh --issue --dns dns_dp -d i.j99.io  -d drive.j99.io -d chat.j99.io -d file.j99.io -d note.j99.io $@
```
![dns](https://user-images.githubusercontent.com/1314740/35181163-c4f31e04-fdf7-11e7-8734-ecc0180522e0.png)

**Comment by ShaRose** [comment]
Assuming I understood through google translate, I think you seem to think it should be outputting a unique certificate per domain. If you pass multiple domains for a single command, it will generate a certificate that matches each domain using SAN (Subject Alternative Name) extensions. In short, this is normal expected behavior. In fact, if you want to check, you can use openssl to verify that it has all the domains using the following command:

openssl x509 -in /var/services/homes/admin/.acme.sh/i.j99.io/i.j99.io.cer -noout -text

(Google Translated)

假设我通过谷歌翻译的理解，我认为你似乎认为它应该是每个域输出一个独特的证书。 如果为单个命令传递多个域，则将生成一个使用SAN（主题备用名称）扩展名匹配每个域的证书。 总之，这是正常的预期行为。 事实上，如果你想检查，你可以使用openssl来验证它具有使用以下命令的所有域：

**Comment by henjue** [comment]
I'm terribly sorry, I understand it wrong. Thank you for your reply！
