### ISSUE TITLE
Still using self-signed after successful install

### ISSUE THREAD

**Issue by bandtank** [Neilpang/acme.sh#1414]
I used --dns_aws to connect to AWS Route 53, which worked just fine. I connected from different browsers in private mode, rebooted the cloud key, and tried the process from the beginning twice. I'm still getting the self-signed key in all instances. Any ideas?

Here's the output from my second run through the process:

```
[Sun Mar 18 09:05:54 CDT 2018] Run pre hook:'touch /etc/ssl/private/cert.tar; tar -zcvf /root/.acme.sh/CloudKeySSL_2018-03-18_09.05.51.tgz /etc/ssl/private/*'
tar: Removing leading `/' from member names
/etc/ssl/private/cert.tar
/etc/ssl/private/cloudkey.crt
/etc/ssl/private/cloudkey.key
/etc/ssl/private/ssl-cert-snakeoil.key
/etc/ssl/private/unifi.keystore.jks
[Sun Mar 18 09:05:54 CDT 2018] Single domain='<removed>'
[Sun Mar 18 09:05:54 CDT 2018] Getting domain auth token for each domain
[Sun Mar 18 09:05:54 CDT 2018] Getting webroot for domain='<removed>'
[Sun Mar 18 09:05:54 CDT 2018] Getting new-authz for domain='<removed>'
[Sun Mar 18 09:05:56 CDT 2018] The new-authz request is ok.
[Sun Mar 18 09:05:56 CDT 2018] <removed> is already verified, skip dns-01.
[Sun Mar 18 09:05:56 CDT 2018] Verify finished, start to sign.
[Sun Mar 18 09:05:58 CDT 2018] Cert success.
-----BEGIN CERTIFICATE-----
<removed>
-----END CERTIFICATE-----

[Sun Mar 18 09:05:58 CDT 2018] Your cert is in /root/.acme.sh/<removed>/<removed>.cer
[Sun Mar 18 09:05:58 CDT 2018] Your cert key is in /root/.acme.sh/<removed>/<removed>.key
[Sun Mar 18 09:05:58 CDT 2018] The intermediate CA cert is in /root/.acme.sh/<removed>/ca.cer
[Sun Mar 18 09:05:58 CDT 2018] And the full chain certs is there: /root/.acme.sh/<removed>/fullchain.cer
[Sun Mar 18 09:05:59 CDT 2018] Installing key to:/etc/ssl/private/cloudkey.key
[Sun Mar 18 09:05:59 CDT 2018] Installing full chain to:/etc/ssl/private/cloudkey.crt
[Sun Mar 18 09:05:59 CDT 2018] Run reload cmd: sh /root/.acme.sh/cloudkey-renew-hook.sh
** Configuring new Let's Encrypt certs
Importing keystore /etc/ssl/private/cloudkey.p12 to /usr/lib/unifi/data/keystore...
Existing entry alias unifi exists, overwrite? [no]: y

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /usr/lib/unifi/data/keystore -destkeystore /usr/lib/unifi/data/keystore -deststoretype pkcs12".
cloudkey.crt
cloudkey.key
** Testing Nginx and restarting
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[ ok ] Restarting nginx (via systemctl): nginx.service.
[Sun Mar 18 09:06:24 CDT 2018] Reload success
```

**Comment by FernandoMiguel** [comment]
Did you try using --force and remove --test?

--
Fernando Miguel

**Comment by bandtank** [comment]
@FernandoMiguel  Thank you for your response. I'm not sure what you mean, but I realize I forgot to include the command I used:
```
acme.sh \
        --force \
        --issue \
        --dns dns_aws \
        -d unifi.pseglobal.com \
        --pre-hook "touch /etc/ssl/private/cert.tar; tar -zcvf /root/.acme.sh/CloudKeySSL_`date +%Y-%m-%d_%H.%M.%S`.tgz /etc/ssl/private/*" \
        --fullchainpath /etc/ssl/private/cloudkey.crt \
        --keypath /etc/ssl/private/cloudkey.key \
        --reloadcmd "sh /root/.acme.sh/cloudkey-renew-hook.sh"
```

**Comment by FernandoMiguel** [comment]
What does the renew hook do?
Seems to be what is failing in your workflow

--
Fernando Miguel

**Comment by bandtank** [comment]
```
#!/bin/bash
# Renew-hook for ACME / Let's encrypt
echo "** Configuring new Let's Encrypt certs"
cd /etc/ssl/private
rm -f /etc/ssl/private/cert.tar /etc/ssl/private/unifi.keystore.jks /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/private/fullchain.pem

openssl pkcs12 -export -in /etc/ssl/private/cloudkey.crt -inkey /etc/ssl/private/cloudkey.key -out /etc/ssl/private/cloudkey.p12 -name unifi -password pass:aircontrolenterprise

keytool -importkeystore -deststorepass aircontrolenterprise -destkeypass aircontrolenterprise -destkeystore /usr/lib/unifi/data/keystore -srckeystore /etc/ssl/private/cloudkey.p12 -srcstoretype PKCS12 -srcstorepass aircontrolenterprise -alias unifi

rm -f /etc/ssl/private/cloudkey.p12
tar -cvf cert.tar *
chown root:ssl-cert /etc/ssl/private/*
chmod 640 /etc/ssl/private/*

echo "** Testing Nginx and restarting"
/usr/sbin/nginx -t
/etc/init.d/nginx restart ; /etc/init.d/unifi restart
```

I followed the instructions [here](https://www.naschenweng.info/2017/01/06/securing-ubiquiti-unifi-cloud-key-encrypt-automatic-dns-01-challenge/). I emailed the author of the article, but it seemed like it was in acme. I guess that's probably not the case, though.

**Comment by FernandoMiguel** [comment]
If you delete the old key and issue a new one, test with openssl or even on
a httpd server will show you the cert is OK or testing.
Acme.sh never generates a self sign cert.
So your issue should be somewhere else where you are deploying

--
Fernando Miguel

On 18 Mar 2018 18:52, "Anthony Andriano" <notifications@github.com> wrote:

#!/bin/bash
# Renew-hook for ACME / Let's encrypt
echo "** Configuring new Let's Encrypt certs"
cd /etc/ssl/private
rm -f /etc/ssl/private/cert.tar /etc/ssl/private/unifi.keystore.jks
/etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/private/fullchain.pem

openssl pkcs12 -export -in /etc/ssl/private/cloudkey.crt -inkey
/etc/ssl/private/cloudkey.key -out /etc/ssl/private/cloudkey.p12 -name
unifi -password pass:aircontrolenterprise

keytool -importkeystore -deststorepass aircontrolenterprise
-destkeypass aircontrolenterprise -destkeystore
/usr/lib/unifi/data/keystore -srckeystore
/etc/ssl/private/cloudkey.p12 -srcstoretype PKCS12 -srcstorepass
aircontrolenterprise -alias unifi

rm -f /etc/ssl/private/cloudkey.p12
tar -cvf cert.tar *
chown root:ssl-cert /etc/ssl/private/*
chmod 640 /etc/ssl/private/*

echo "** Testing Nginx and restarting"
/usr/sbin/nginx -t
/etc/init.d/nginx restart ; /etc/init.d/unifi restart

I followed the instructions here
<https://www.naschenweng.info/2017/01/06/securing-ubiquiti-unifi-cloud-key-encrypt-automatic-dns-01-challenge/>.
I emailed the author of the article, but it seemed like it was in acme. I
guess that's probably not the case, though.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Neilpang/acme.sh/issues/1414#issuecomment-374032582>,
or mute the thread

**Comment by bandtank** [comment]
Thanks for your help.
