### ISSUE TITLE
Only RSA or EC Key is supported.

### ISSUE THREAD

**Issue by ReptoxX** [Neilpang/acme.sh#146]
Hi,

So now i wanted to create the Certs again and i am facing a new error.
When i use "acme.sh --issue --apache -d xxxx.com" i am getting this response:
Only RSA or EC key is supported.

Regards,
ReptoxX

**Comment by Neilpang** [comment]
please add `--debug`
```
 acme.sh --issue --apache -d xxxx.com  --debug 
```

**Comment by reptoxx** [comment]
Okay i just did.

> [TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:1:Le_Domain=reptoxx.com
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:2:Le_Alt=no
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:3:Le_Webroot=apache
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:4:Le_Keylength=no
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:5:Le_RealCertPath="no"
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:6:Le_RealCACertPath="no"
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:7:Le_RealKeyPath="no"
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:8:Le_ReloadCmd="no"
[TIME] /root/.acme.sh/reptoxx.com/reptoxx.com.conf:9:Le_RealFullChainPath="no"
[TIME] Backup apache config file='/etc/apache2/apache2.conf'
[TIME] JFYI, Config file /etc/apache2/apache2.conf is backuped to /root/.acme.sh/apache2.conf
[TIME] In case there is an error that can not be restored automatically, you may try restore it yourself.
[TIME] The backup file will be deleted on sucess, just forget it.
[TIME] apacheVer='2.2.22'
[Sat Apr 16 12:10:34 2016] [warn] The Alias directive in /etc/apache2/apache2.conf at line 279 will probably never match because it overlaps an earlier Alias.
[Sat Apr 16 12:10:34 2016] [warn] The Alias directive in /etc/apache2/apache2.conf at line 287 will probably never match because it overlaps an earlier Alias.
Syntax OK
[Sat Apr 16 12:10:34 2016] [warn] The Alias directive in /etc/apache2/apache2.conf at line 279 will probably never match because it overlaps an earlier Alias.
[Sat Apr 16 12:10:34 2016] [warn] The Alias directive in /etc/apache2/apache2.conf at line 287 will probably never match because it overlaps an earlier Alias.
[TIME] Only RSA or EC key is supported.

And their is one other problem, he did not restore the original apache2.conf after this error.

Regards

**Comment by Neilpang** [comment]
Please  check your `account.key`  and `domain/domain.key` file. 
I guess either one of the is empty.

**Comment by ReptoxX** [comment]
Okay i works right now, i just removed account.key file and its now generated correctly

Thank You for the fast solution.

**Comment by Neilpang** [comment]
Glad to see it works for you.

I just made a fix for you to restore apache more on error.

5ef501c5ece35003eaa341f1c73b6838b0bbe528

Please update the latest code and try again.

**Comment by cthart** [comment]
I managed to still get this error. What happened:
I installed Let's Encrypt.
I ran `acme.sh --issue ...` but realised I forgot to set the DNS username/password variables, so I pressed ^C right after the line "Using CA: https://acme-v02.api.letsencrypt.org/directory" appeared.

Then I set the DNS username/password variables and ran the issue command again. Boom, got this error.
I realise that my configuration was in an error state, but being able to recover automatically would be nice.
