### ISSUE TITLE
not working with sh on Ubuntu 14.04

### ISSUE THREAD

**Issue by pfaffman** [Neilpang/acme.sh#153]
It's not working with the `/usr/bin/env sh` that's on Ubuntu 14.04 LTS:

```
root@scc:~/acme.sh# ./acme.sh 
./acme.sh: 26: ./acme.sh: [[: not found
./acme.sh: 2264: ./acme.sh: [[: not found
./acme.sh: 2270: ./acme.sh: [[: not found
```

Changing `sh` to `bash` works fine.

**Comment by jenssegers** [comment]
Having the same issue.

**Comment by thelinuxfr** [comment]
Same issue on Debian Jessie. Maybe problem with dash shell ?

**Comment by thelinuxfr** [comment]
Work with :

dpkg-reconfigure dash

Use dash as the default system shell (/bin/sh)? <- no

**Comment by pfaffman** [comment]
Perhaps there's something I'm missing, but if whatever the default system shell is doesn't work with the script then I don't see an advantage to removing the dependency on bash. There aren't many systems that don't have bash installed.

**Comment by Neilpang** [comment]
sorry, guys, 
It's reverted to bash now.  please try again.
8663fb7e64e5e3a712c39f2d2cb7cf6bca7b5ef0

**Comment by thelinuxfr** [comment]
@Neilpang works for me (I restored dash default)

**Comment by Neilpang** [comment]
Hi guys,
Sorry, for the previous trouble.

With the latest v2.2.2(I checked in one day ago),  acme.sh is  bash/dash/sh compatible.   
When installing, if bash is installed, it will prefer to use bash first for a higher performance.  

Otherwise, it can also work in dash and pure sh.  I have tested with ubuntu dash, and FreeBSD sh.

Thanks.
