### ISSUE TITLE
TLS-ALPN validation method

### ISSUE THREAD

**Issue by hebbet** [Neilpang/acme.sh#1675]
the tls-alpn-01 challange was added to staging yesterday

https://community.letsencrypt.org/t/tls-alpn-validation-method/63814/2

**Comment by Neilpang** [comment]
Let's wait and see how many users need it.

**Comment by jim-p** [comment]
We have had a few requests from users who would like port 443 validation back. The security issues with TLS-SNI were unfortunate. Some users are stuck in situations where they can't use a DNS method and their ISP blocks port 80 but not 443. It would be nice to have, but I wouldn't consider it a priority since there are other working methods available.

TLS-ALPN is also available for production use now: https://community.letsencrypt.org/t/tls-alpn-validation-method/63814/3

**Comment by yecarrillo** [comment]
Please add TLS-ALPN. I have been 7 months with manual validations

**Comment by flowercow** [comment]
need ALPN

**Comment by flowercow** [comment]
Does ALPN challenger has a development plan?

**Comment by Neilpang** [comment]
fixe, close
