### ISSUE TITLE
Revoke and delete directory?

### ISSUE THREAD

**Issue by CarloMartini** [Neilpang/acme.sh#1709]
Hello,
Suppose I issue a certificate with a typo. If I revoke it, it will still appear on --list, unless I use 

`rm -rf .acme.sh/wrong_dir`

(That should be equivalent to --remove)

Is there a way to automatize this process? That is, to both revoke and remove the dir?

**Comment by Neilpang** [comment]
Sorry, you have to delete the folder by yourself for now.

We don't have an option to delete it automatically.  Since the folder contains critical data: such as your config or private domain key etc,  we never delete any of the critical data on your system, no matter in ".acme.sh" folder or anywhere in your system.  It's designed to keep your system safe.

Thanks.
