### ISSUE TITLE
Cleanup old DNS TXT records

### ISSUE THREAD

**Issue by klamann** [Neilpang/acme.sh#2037]
I recently stumbled upon an issue where due to a number of failed ACME challenges, several DNS TXT records have been set by acme.sh through the API of my DNS provider, but they were never deleted. 

The DNS records were set by the [`dns_dynu.sh`](https://github.com/Tigger2014/acme.sh/blob/master/dnsapi/dns_dynu.sh) plugin, but because dynu.com has a pretty low limit for the number of DNS records that can be set, further requests to their API failed with a "Quota Exception" message.

Can we change the challenge-response process in a way that the TXT records set through one of the dnsapi plugins are always removed, even if the request fails and no certificate is issued? Or maybe check that all TXT records that have been set in a previous session have actually been deleted, when a new certificate is requested? That way we can make sure that old records don't pile up, even if the process is is terminated right after the TXT records have been set.

**Comment by Neilpang** [comment]
please try again.

**Comment by JMC-PK** [comment]
Id like to say that this is still occurring on 2.8.2.

I frequently have old empty text records when using the dns api with GoDaddy.

Since they are empty, it is partially cleaning up and I know which are safe to delete manually, but it should remove the whole record itself.

![Screen Shot 2019-08-08 at 10 52 16 AM](https://user-images.githubusercontent.com/29738399/62713427-b738dc00-b9ca-11e9-8cc8-0c22bdb5f10e.png)
![Screen Shot 2019-08-08 at 10 52 31 AM](https://user-images.githubusercontent.com/29738399/62713435-bacc6300-b9ca-11e9-9c4c-f214e068bf9a.png)
