### ISSUE TITLE
Client sent me a csr I'm supposed to use...

### ISSUE THREAD

**Issue by serker1** [Neilpang/acme.sh#212]
Can't figure out if I'm missing a flag or something, but I can't seem to specify using their csr.  acme.sh simply replaces the csr with it's own on --issue --dns.

Attempted creating a standard cert, then replaced the csr in the directory with theirs, but acme.sh balks at it (Creating CSR).  Same with --renew.

Also attempted using their private key, but new csr is created same as above.  I"m thinking a --useCSR (-ucsr) might be in order to solve this, but I'm shooting in the dark here.  Any suggestions welcome--I just assume at this point I'm missing something obvious...

**Comment by Neilpang** [comment]
You are totally right.  Each time we issue cert, the csr is generated again.  Only the private key and the domains are considered.

As currently,  let's encrypt server,  they only use the public key and domain names from the csr,  any other info in the csr will be ignored.

So it's meaningless to use a customized CSR.

**Comment by drscriptt** [comment]
I have a 3rd party application that I want to use a Let's Encrypt certificate for.

The problem is, the application controls cert generation & management.  The only thing I can do is 1) download a CSR that it generates, 2) get the CSR signed, and 3) upload the certificate into the application.  (This is not uncommon.  I've run into it a **lot** of times.)

So, it is _not_ meaningless to use a customized CSR.

Is there a way that acme.sh can be made to work with existing CSRs?

**Comment by Neilpang** [comment]
@drscriptt 
Good,  let me think about it again.

**Comment by Neilpang** [comment]
Hi @drscriptt 
It's fixed.
Please see:  https://github.com/Neilpang/acme.sh/wiki/Issue-a-cert-from-existing-CSR

**Comment by drscriptt** [comment]
Thank you!!!

That worked exactly as I needed (and wanted) it to.

:-)

**Comment by za3k** [comment]
Thanks, this is great
