### ISSUE TITLE
Add option on --install to skip cron job installation

### ISSUE THREAD

**Issue by tinproject** [Neilpang/acme.sh#220]
For automation purposes it would be good to have an option to skip the cron job install. So if someone wants to add a custom cron job at a custom time don't have to remove the cron job added by default at install time.

A good parameter option could be `--noinstallcronjob`.

Thanks for this great tool!

**Comment by Neilpang** [comment]
If you don't like the default cron job,  you can use `--uninstallcronjob` command to remove the cron job after you install it.
For example:

```
#install acme.sh
./acme.sh  --install

# Then remove the cron job:

acme.sh  --uninstallcronjob

```

**Comment by tinproject** [comment]
Yes, but if you install again (to update, or by an idempotent process: Ansible), the cron job installs again. Then you have to uninstall it again, and `--uninstallcronjob` wipes every cron job that points to the same `path/acme.sh --cron`, so you have to install the custom cron job again.

It will be much more simple if there is an option to skip the cron job installation. 

I could write a PR if you wish.

**Comment by Neilpang** [comment]
fixed:  c8e9a31ee5d2ec7622f02dca75221f4d9f9445e4

```
./acme.sh  --install  --nocron
```

**Comment by tinproject** [comment]
Thanks, works perfectly!!

**Comment by jessuppi** [comment]
I'm a few years late, but this is awesome... I didn't immediately realize that `acme.sh` could be installed without any cron jobs, hence my discussions with some of the Lets Encrypt folks.

Ref: https://community.letsencrypt.org/t/which-lets-encrypt-client-should-slickstack-use/142256
Ref: https://community.letsencrypt.org/t/brief-overview-of-steps-that-certbot-api-goes-through/141892

In SlickStack we manage (overwrite) the root `crontab` and any custom cron jobs must be added in `ss-config` so that they will be called according to our hardcoded schedule; now that I know `acme.sh` can be set on a custom schedule, we are going to proceed with testing this as part of our SSL renewal scripts (currently we use Certbot).

Ref: https://github.com/littlebizzy/slickstack/blob/master/ss-encrypt-acme.txt

**Comment by Neilpang** [comment]
@jessuppi 

See `acme.sh --help`

and  https://github.com/acmesh-official/acme.sh/wiki/Options-and-Params

you will find a lot of useful options.

**Comment by Neilpang** [comment]
@jessuppi  you may also be interested in this wiki: https://github.com/acmesh-official/acme.sh/wiki/How-to-install

**Comment by jessuppi** [comment]
Thanks mate you're a machine! @Neilpang 

I'm not sure why those pages didn't show up in my initial Google searches, but luckily this GitHub Issue did :)
