### ISSUE TITLE
Unwanted shell expansion L3859

### ISSUE THREAD

**Issue by non7top** [Neilpang/acme.sh#2256]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```
There is an unwanted shell expansion happening on line 3859
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L3859

_idn $d
if $d contains wildcard (*.ex.com) it can match the file present in current directory (/root by default) if there is a file ex.ex.com $d will be polluted

should be like this https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L3856

**Comment by LuSo58** [comment]
Not sure if it's the same thing I've just had trouble with, but for me, it expanded to some subdomain, because I was in my `sites-enabled` folder, where all configs are named by their domains. So the expansion used the alphabetically first filename in the directory. After I moved to an empty folder (or one, that does not contain any "expandable to" contents), it started working.

**Comment by Neilpang** [comment]
fixed,  please try with the latest dev branch:
```sh
acme.sh --upgrade -b dev
```
