### ISSUE TITLE
will you update for "End of Life Plan for ACMEv1"

### ISSUE THREAD

**Issue by miltosc** [Neilpang/acme.sh#2378]
Hello,
will you update acme.sh for End of Life Plan for ACMEv1?

https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

Thanks in advance for your answer

**Comment by Neilpang** [comment]
it has been a long time that we are using  ACMEv2 by default.
We don't use ACMEv1 unless the user forces it to.

**Comment by miltosc** [comment]
Thank you for your quick answer!

**Comment by SomeoneElseOSM** [comment]
Just to clarify (since I've just tripped over this today) "We don't use ACMEv1 unless the user forces it to" seems to include "or the certificate was originally issued a very, very long time ago", and the fix is https://github.com/acmesh-official/acme.sh/issues/3172#issuecomment-692098117 - "and try issue again" means of course ''don't try and renew your existing certificate with --renew, issue a new one with --issue".
