### ISSUE TITLE
Le_ReloadCmd Base64?

### ISSUE THREAD

**Issue by sjau** [Neilpang/acme.sh#2444]
Steps to reproduce
------------------

After a long time looking at the .conf files again I noticed that the reload command has been turned into a base64 string. Why?

This is troublesome when I want to check what the reload command actually was that was originally setup with.

**Comment by Neilpang** [comment]
yes,   the reloadcmd may contain some special chars.

Don't rely on the conf file,  it's for internal use only.

If you want to get the reloadcmd,  maybe,  we can print it in the `--list` command as a new column.

what do you think?

**Comment by sjau** [comment]
While a getting the reloadcmd output with the `--list` command would be an improvment, I still think it's very strange that you base64 encode thing in a config file.

I can't think of any .conf file on a *nix system that can't be easily edited with a text editor. I fail to see why you chose such an approach and making it harder to edit the config files.

**Comment by Neilpang** [comment]
@sjau 
As always,  acme.sh keeps compatible with the old format.
Which means, you can(but not recommended to) edit the config file, with plain format(non-base64 format).

Anyways, if you want to read/edit any values in the config,  please create a request issue,  we can add a new public command line parameters to support it.
It's not encouraged to edit the config files manually. It's for internal use only.
The config format can change, and it might be possible that one day, we could use SQLite instead of plain config files.

So, don't rely on it.

**Comment by Jas0n99** [comment]
Yeah, this threw me for a loop when upgrading... I spent way more time than necessary thinking something jacked my config file and dumped the wrong line in there. Which that only came up because the change from bash to sh broke my reload statement as it didn't like having <(echo) in the string.

I just removed the base64 encoding as I rarely mess with acme, but when I do it seems like I have to relearn everything to do any basic commands. Whereas one could just edit the config files directly and be done much quicker.

Keep it simple!

**Comment by Ressy66** [comment]
and just found when it converted existing to base64  it wiped out the reload command to nothing, nudda, empty on a couple of zones.
likely because we HAD it do things that shell required commands inside ( ) since all others appear to be ok only the ones with those sub commands were affected.
We used ( ) becasue it kept failing on 
 cat /path/1 /path/2  > foo.pem && /etc/rc.d/rc.daemon_1 reload && /etc/rc.d/rc.daemon_2 reload ...

**Comment by Ressy66** [comment]
Neil,
can we have an option to disable this base64, again I found alerts for expiring domains not updated because encoding,  they were updated on disk but the script is screwing up when its base64 encoding the reloadcmd, again half the command is missing, its a PITA - these tyroubles only started when the code was changed to base64 encode the reloadcmd, before that fora long time never had problem

**Comment by vebmaster** [comment]
also seemed strange to use base64 for reloadCmd string

**Comment by vebmaster** [comment]
Hello. 
How can I see the command encoded in base64?

**Comment by Neilpang** [comment]
I just added a new command `--info` to show the global configs or the domain configs,  please upgrade to the latest `dev` branch first.

```
acme.sh  --upgrade -b dev
```


```
#show global configs:

acme.sh --info
```

```
#show the domain configs:
acme.sh --info  -d example.com
```

**Comment by digitalfredy** [comment]
I waste tons of time grepping and searching to find which command I decide to execute, this is really not a UNIX  alike approach and I must to say that I disliked it as admin, is like systemd and this horrible thinking of creating new tools to do what we where capable to do with standard tools like grep and tail.

It makes no sense for me but I guess you are the own acme.sh and you decide where it goes then even if I dislike this point thanks anyway for doing it ;)
