### ISSUE TITLE
Can you modify a certificate using --renew

### ISSUE THREAD

**Issue by Omoeba** [Neilpang/acme.sh#2445]
If I wanted to add the --ocsp parameter to my certificate, can I use --renew --force instead of issuing a new certificate?

**Comment by zhanhb** [comment]
I finish that by two commands.
```
acme.sh --createCSR --ocsp -d 1.1.1.1.16clouds.com -w /www
acme.sh --renew -d 1.1.1.1.16clouds.com --force
```

**Comment by Neilpang** [comment]
It's not recommended to MODIFY  a cert when renewal.

It's designed that the renewal is just a `"redo"`  of `issue`.   Which ensures that there is no exceptions/surprises in the renewal.

Because the renewal is always expected to run automatically in the cronjob,  we must make sure renewal successes as long as the issue succeeded.

That's why we don't modify anything for `renew`.

You want a new cert, just issue a new one.  You will get no surprises in the middle night when you are sleeping.
