### ISSUE TITLE
I do not have DDNS *.synology.me key, how to proceed?

### ISSUE THREAD

**Issue by ctrngk** [Neilpang/acme.sh#2494]
I want to use DDNS  *.synology.me,  but I need an *API key*, which I cannot find in the official site.  Is it ok to ignore **dnsapi** and continue? 
https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide

**Comment by FernandoMiguel** [comment]
@ctrngk you can't issue a cert for a domain you don't own

**Comment by ctrngk** [comment]
I see. Witout *key*, many different people can repeatedly request the same process over and over again.

The Synology by default issue Let's Encrypt for me, right after creating a *.synology.me DDNS. However, this failed because my ISP blocks 80 port.

What I infer from your comment, I do not own *.synology.me (even though I create this from the device), so there is no way I could issue a cert, unless Synology, the owner, provide the key or do it for me, like what I mention above.  Am I correct?

**Comment by FernandoMiguel** [comment]
@ctrngk you can't using DNS validation, which is the prefered method.
and as you said, having port 80 blocked, won't let you use IP validation either.

It would be prefered for you to use your own domain, where you can control the DNS zone

**Comment by ctrngk** [comment]
I see. There are two validation, DNS (key) or IP (:80) validation. Thank you for your patience. I am just being lazy to maintain my own domain. I just simply want the HTTPS to work as simple as possible.

**Comment by rhawk301** [comment]
You are certainly not lazy. I use the <hostname>.synology.me and use a CNAME with my dns provider. It gives me a way to use my domain and map the synology ddns.  The LE cert does in fact have to use port 80, I tested it several ways.

Now. On to business.  I have updated to DSM 6.2.2 and I clearly see from the logs that a DNS-01 method is attempted on your personal domain, but fails because in my case, I did not configure a DDNS provider that allows updates via the ACME method.  My <hostname>.synology.me works just fine, as it uses a proper DDNS provider that Synology supports.

Since the acme.sh script supports dns-01 methods, just like certbot, I would imagine the Synology software "szUserAgent" can support this as well.

I believe it would change your personal dns entry, as long as you configure a DDNS provider which allows for such changes and modifying/creating a TXT record for _acme-challenge.<domain.tld>

I need to do more investigation, but anyone who might also be experimenting with native cert creating using custom ddns, please also chime in. The problem still remains, its not the best practice opening your DSM to the internet.
