### ISSUE TITLE
Acme letsencrypt server returns 500 error

### ISSUE THREAD

**Issue by claytonrothschild** [Neilpang/acme.sh#2599]
Hi,

The letsencrypt acme instance appears to be down:

```
[Thu Nov 21 16:38:03 UTC 2019] RSA key
[Thu Nov 21 16:38:03 UTC 2019] HEAD
[Thu Nov 21 16:38:03 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Nov 21 16:38:03 UTC 2019] _CURL='curl -L --silent --dump-header /home/sslService/.acme.sh/http.header  -g '
[Thu Nov 21 16:38:03 UTC 2019] _ret='0'
[Thu Nov 21 16:38:04 UTC 2019] POST
[Thu Nov 21 16:38:04 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Nov 21 16:38:04 UTC 2019] _CURL='curl -L --silent --dump-header /home/sslService/.acme.sh/http.header  -g '
[Thu Nov 21 16:38:04 UTC 2019] _ret='0'
[Thu Nov 21 16:38:04 UTC 2019] code='500'
[Thu Nov 21 16:38:04 UTC 2019] Le_LinkOrder
[Thu Nov 21 16:38:04 UTC 2019] Le_OrderFinalize
[Thu Nov 21 16:38:04 UTC 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Error creating new order",
  "status": 500
}
```

Any suggestions? Thank you.

**Comment by claytonrothschild** [comment]
I made a post on Lets Encrypt to alert to this situation: https://community.letsencrypt.org/t/is-the-acme-v2-staging-server-working/106912

**Comment by cpu** [comment]
:wave: Hi folks. Updating this thread with what we found in the community forum.

The root cause of the problem was that the order had more than 100 names. That should give a meaningful error that tells the user what the problem is but there was [a bug in Boulder](https://github.com/letsencrypt/boulder/issues/4571) that made Let's Encrypt return a 500 error instead. We're [fixing that now](https://github.com/letsencrypt/boulder/pull/4572) and after next week's deployment this case will return a clear error like:

> Error creating new order :: Order cannot contain more than 100 DNS names

Instead of just:

> Error creating new order

**Comment by claytonrothschild** [comment]
Excellent. Thank you for the help @cpu and everyone in the forum. Closing ticket as resolved.
