### ISSUE TITLE
DNS request fails with "Response does not complete challenge"

### ISSUE THREAD

**Issue by pcolmer** [Neilpang/acme.sh#267]
I'm trying to request a certificate using the DNS method. However, when I run acme.sh with --renew, I get this error:

Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: Response does not complete challenge","status": 400}

I'm not sure what this means or how to fix it.

**Comment by Neilpang** [comment]
because the dns record doesn't take effect before your run `--renew`

Please wait until it takes effect, then run `--renew`.

**Comment by pcolmer** [comment]
Ah - thanks for clarifying that.

**Comment by NikLP** [comment]
It's not clear to me - what happens if you run renew before the propagation takes place?

How do you know if it's worked? I use Linode; I can add an A record for _acme-challenge.mydomain.com, but any TXT record isn't obviously bound to that record. It is just a generic TXT in the pool associated to the main domain.

Furthermore, I can't add _acme-challenge.subdomain.domain.com, it gets curtailed after the subdomain; does this matter?

I really think an end to end example of *exactly* how to implement this would be useful, I've been looking for days and can't find anything truly simple - at least nothing that explains the pitfalls if you don't wait, how to test for readiness etc etc.

**Comment by Neilpang** [comment]
@NikLP 

If you don't know how to add txt record in linode,  please search google for:
```
how to add txt record in inlinode  
```

If you don't know whether the txt record takes effect:

```
dig  _acme-challenge.mydomain.com  txt

```
or
```
dig  _acme-challenge.subdomain.domain.com   txt
```

**Comment by NikLP** [comment]
I've described as best I can how I see the TXT records in Linode. I thought that made it clear I have added them, so know how to? :) It just isn't obvious that the TXT records are bound to an exact domain/A record. 

I've queried against the linode dns but I see no results in the dig. I also can't find a reference anywhere that binds an A record to a TXT record, and this isn't illustrated in the setup anywhere or *any* of the issues I've seen. I feel like there's a part of the setup docs missing :(

**Comment by Neilpang** [comment]
@NikLP 

Sorry, but you may need some more knowledge about  dns records.

`A record` has totally nothing to do with `TXT record`.  They are two different types, something like  `dog` and `cat`.  Do not misunderstand them.

When we say `dns records` for acme, we definitely mean `TXT record`,  there is nobody mentioned a `A record`.

 You just need to add a `TXT record` to the domain/sub-domain,  wait for the record to take effect, then retry.

I think it's clear enough.

**Comment by NikLP** [comment]
Oh no I get it, I just am struggling then in the Linode UI, which only gives me this - there's no place to "bind" it to a sub/domain.

![kstxt](https://cloud.githubusercontent.com/assets/2248659/20063593/b592c2ea-a4ff-11e6-93f4-4ae9d96fbb24.png)
