### ISSUE TITLE
dns mode staging cert ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#269]
in the example

    acme.sh --issue --dns -d aa.com -d www.aa.com

if i want staging cert i only need to pass --staging flag here ?

    acme.sh --issue --staging --dns -d aa.com -d www.aa.com

and don't need to for renew ?

    acme.sh --renew -d aa.com

or do i need for renew too ?

    acme.sh --renew --staging -d aa.com

**Comment by centminmod** [comment]
ah don't need it for --renew as --issue --staging already has the staging csr/key

**Comment by Neilpang** [comment]
Hi @centminmod ,

1) yes,  `--staging` is also working for   `--dns` mode.
```
acme.sh --issue  --staging   --dns   .......
```

2) No,  `--staging`  is also needed for  `--renew`,   if you don't specify `--staging`,   the `--renew` will renew the cert against the production server.   Which means, if you issue a test cert first,  it will be renewed as a production cert after 80 days automatically.

This is because I think `--staging` or `--test`  is just a temp case for test or debugging.  When you are sure every thing is ok, you should go with the production server.

**Comment by centminmod** [comment]
thanks @Neilpang :)
