### ISSUE TITLE
randomise crontab

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#302]
in order to avoid having all servers ping the API servers at the same time for renewal, 
I've added this to our cron

sleep $(expr $RANDOM \% 90) &&

so the crontab code looks like
      crontab -l | { cat; echo "30 2 * * 1 sleep $(expr $RANDOM \% 90) && $lesh --cron --home \"$LE_WORKING_DIR\" --post-hook service nginx reload > /dev/null"; } | crontab --

maybe consider upstreaming this ?

**Comment by Neilpang** [comment]
NO.

It will ping the server only when the cert expired.

Never, never change the default cronjob, unless you know well about acme.sh

**Comment by FernandoMiguel** [comment]
the reasoning for this crontab change is that we have several frontend servers and would not like all of them to change the cert at the same time.
randomising it allows for the change to happen over time

**Comment by Neilpang** [comment]
@FernandoMiguel 
There are 2 errors in your code:

1.  Do not use "$LE_WORKING_DIR" in the cronjob.  it may not be defined when cronjob is running.
That's why we have a `--home` parameter.

```
acme.sh  --cron  --home "/path/to/acme.sh/home"
```

2.  Do not use `--post-hook service nginx reload`  in cronjob.

You can issue a cert with `--post-hook`
```
acme.sh --issue  ......    --post-hook  "service nginx reload"
```

The post hook will be recorded automatically.  And when the cert is renewed after 80 days by `--cron` command,  the post hook will be executed automatically.   You don't need to add a `--post-hook` to the cron job.

Just simply use `--cron`:
```
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```


keep it simpe,  acme.sh is smart enough to process most of the stuffs, such as check the expire time, pre/post hooks etc.

If you want it randomly, you can just change the time entry of the cronjob:

```
0 1 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

**Comment by FernandoMiguel** [comment]
the example was taken from your piece of code in acme.sh where it builds the crontab entry.
glad to learn that --cron will use the post hook if one is used initially 


Maybe I'm not making myself clear regarding the random.
say you have 10 servers. and at 1am all of them will check to see if the cert needs to be update, and all of them will sign new certs, all of them will update the DNS entries, all of them will nginx reload **AT THE SAME TIME**
now make that 1000 servers , as I manage.
it's a problem :)

but ok, i'll script my crontab to include the random on our install

thank you for explaining it to me.
