### ISSUE TITLE
Contibuting a DNS API script

### ISSUE THREAD

**Issue by noplanman** [Neilpang/acme.sh#343]
How exactly does the contributing of a custom DNS API script work?
I would need to create a new PR every time I update something in the script, right?

Also, the one that I've been working on is for a domain hosting in Switzerland called [cyon](https://cyon.ch) (.ch and .li domains). Does it even make sense to add it to this repository or would it make more sense to just add a link in the readme somewhere?

And lastly, they don't have an official API yet, so it's basically cURL calls to do the authentication and add/delete of the DNS entries. Is that ok too? Or does it "have to" be an API?

Thanks!

**Comment by Neilpang** [comment]
>> I would need to create a new PR every time I update something in the script, right?
Yes,  if you fix bugs in the script, please create a new PR to push in.
Also, please place a link in the api script file, so that if there is a bug found, someone know where  to file bugs.


>> Does it even make sense to add it to this repository or would it make more sense to just add a link in the readme somewhere?

Yes,  It's welcomed to support any dns apis.

>>  And lastly, they don't have an official API yet, so it's basically cURL calls to do the authentication and add/delete of the DNS entries. Is that ok too

Yes,  do what you need here, as long as:

1. keep it  shell only.  Do not add more dependencies.  common tools, such as curl, wget, grep or sed etc are ok to use.  do not depend on python or perl etc.
1. keep it  `sh` compatible,  do not use  bash-only syntax.  We need to cross platforms between Linux/BSD/Mac.
1. using the same coding style as the main script.

**Comment by noplanman** [comment]
> Do not add more dependencies.

At the moment I'm using `jq` for the JSON parsing (which really is super-duper helpful, would have to see how to do this differently) and `oathtool` if 2 Factor Authentication is enabled on the account.

> keep it sh compatible, do not use bash-only syntax

How can I check this? I'm not sooo fluent in bash-ish yet 😕

**Comment by sjau** [comment]
@noplanman 

Here's a list of a few bashism - things that are only available in bash and not posix: http://mywiki.wooledge.org/Bashism. Also if you're testing your script as standalone, you could add `set -o posix` to behave more posix-like.

**Comment by Neilpang** [comment]
Hi @noplanman  @sjau 

I have travis CI enabled now,  just send pull requests,  the travis CI will check if your code is posix.

Thanks.

**Comment by noplanman** [comment]
@Neilpang @sjau 
Thanks for all the info. I need to test my script again to make sure it properly deletes the entry and make sure that it's posix-friendly.

Happening soon 👍

**Comment by noplanman** [comment]
Closing here, as the discussion is on the PR itself now: #414
