### ISSUE TITLE
Separate executable code and data store into separate directories

### ISSUE THREAD

**Issue by dkerr64** [Neilpang/acme.sh#539]
We are in the midst of adding acme.sh into the Astlinux project (http://www.astlinux-project.org/) and have found that we need to implement some work-arounds because acme.sh requires (or rather assumes) that both the executable scripts (acme.sh, deploy and dnsapi) are in the same working directory / home directory as data files (account.conf, ca files, http.header, etc.).

While we can work around this for now, I would like to request that acme.sh be modified to allow separation of executables and data into separate directories (ideally acme.sh should be something like just acme in /usr/sbin).  Arguably deploy and dnsapi could be elsewhere like /etc/acme those are not causing the problem.

Thank you
David

**Comment by Neilpang** [comment]
Hi @dkerr64 ,

I understand that mixing up the bin and configs is a pain.

I will add a new parameter like: `acme.sh --config-home "/etc/acme/  ....  "` soon. So that all the config will be written to the config path.

For now, as a temp workaround,  please use `acme.sh --home "/etc/acme/" ... ` instead.

**Comment by dkerr64** [comment]
Thank you.  

we are using --home but that is used for both data and executables... and we need to separate acme.sh into a different directory from the data files.  The specific problem we had was --installcronjob which looks for acme.sh in the same directory as the data files and failed.  So that is the test case.

David

**Comment by abelbeck** [comment]
Good to hear @Neilpang , but may I suggest you instead add a ```--script-home``` option to determine where the acme.sh, deploy and dnsapi scripts are located, not a --config-home option as you proposed.

It would be better to keep ```--home``` (LE_WORKING_DIR) to be where the working data is stored, ```/etc/acme```.  Doing otherwise would break the current workaround as well as all the crontab entries.

For example, users could define ```--home /etc/acme``` and ```--script-home /usr/share/acme``` and current crontab entries would work with the scripts located elsewhere.

Of course extracting all the repo files in one directory would continue to work by default.

**Comment by heldchen** [comment]
@abelbeck `script-home` is sort of implicit given by the location of the script (acme.sh) you're executing. as I read it, the goal in this issue is to separate the configs from the scripts, so f.e. that the acme.sh script could be packaged according to any given linux distribution rules (i.e. config files in /etc, script files in /var/lib etc)...

**Comment by Neilpang** [comment]
@heldchen  yes

**Comment by dkerr64** [comment]
@heldchen only user data files should go in ~/ not system data files.  As certificates are issued to the system URL and system services (the HTTPS server is a system service) then acme.sh data and config files should go in a system directory not user home. 

David

**Comment by heldchen** [comment]
yes, that's what I wrote, @dkerr64 ....

**Comment by Neilpang** [comment]
Hi @dkerr64 

I just added `--config-home` into the `dev` branch.  https://github.com/Neilpang/acme.sh/commit/27dbe77fad0e59ad9bce55df8d165ca512be0c65

If you want to use a separate config folder, it is required to add `--config-home` to any command of `acme.sh`.
For example:

```bash
acme.sh --install   --config-home  /etc/acme.sh

acme.sh  --config-home "/etc/acme.sh"  --issue -d xxx.com ......

acme.sh --config-home  "/etc/acme.sh"   --renew .....  
```

You should have an alias or wrapper:
```bash
acme_cmd="acme.sh  --config-home /etc/acme.sh"
```

Tell me if you have any issues.

I will merge it to master once enough testing.

Thanks.
