### ISSUE TITLE
[Question] Recreate account from existing certificate/private key to renew/expand certificate

### ISSUE THREAD

**Issue by chinkung** [Neilpang/acme.sh#830]
I have lost ALL data in ~/.acme.sh/ except issued certificate and private key and want to know if I can re-create the account from them in order to use it to renew/expand certificate (Add new domain to the same certificate)

**Comment by Neilpang** [comment]
You can not recover your account anymore, but you can still use the same domain cert and key to renew cert.

Just install acme.sh again, and copy the domain cert/key file to the same position in `~/.acme.sh/`.

then you can issue cert again,  your account will be created with a new account key.  When you issue/expand the cert, the domain private key will not be changed.

Thanks.

**Comment by chinkung** [comment]
Could you please shed me some light on folder structure ?

Are these correct ?

**RSA certificate**
~/.acme.sh/<domain>/<domain>.crt
~/.acme.sh/<domain>/<domain>.key

**ECC certificate**
~/.acme.sh/<domain>_ecc/<domain>_ecc.crt
~/.acme.sh/<domain>_ecc/<domain>_ecc.key

Thank you

**Comment by Neilpang** [comment]
yes,  you are right.

but for  ECC certificate
```
~/.acme.sh/domain_ecc/domain.crt
~/.acme.sh/domain_ecc/domain.key
```

**Comment by chinkung** [comment]
When I tried to renew, it seems don't know the domain

$ acme.sh --renew -d **domain** -w /path/to/**domain**/
[Mon May  8 04:34:15 UTC 2017] Renew: '**domain**'
[Mon May  8 04:34:15 UTC 2017] '**domain**' is not a issued domain, skip.

Is there anyway to re-create ~/.acme.sh/**domain**/**domain**.conf in order to let acme.sh renew existing certificate ?

**Comment by chinkung** [comment]
I have recreated ~/.acme.sh/**domain**/**domain**.conf with these content and it allows me to renew

```
Le_Domain='**domain**'
Le_Alt='no'
Le_Webroot='/path/to/**domain**/'
```

**Comment by FernandoMiguel** [comment]
> When you issue/expand the cert, the domain private key will not be changed.
@Neilpang can you please explain this a bit better?
thanks

**Comment by Neilpang** [comment]
@FernandoMiguel 

If use use `--issue` or `--renew` multiple times on the domain,  the private key is only generated for the first time,    the private key will not be changed unless your delete the key file explicitly by your hand.

**Comment by FernandoMiguel** [comment]
@Neilpang so you are able to use a different private key from another Account key?
:O

**Comment by Neilpang** [comment]
@FernandoMiguel 
Yes,  the domain key and the account key has no relation.

**Comment by FernandoMiguel** [comment]
so if someone compromise the private key they can use another account key to keep renewing the key and decrypt all the previous/past traffic and new traffic with MITM ?

**Comment by Neilpang** [comment]
@FernandoMiguel 
No,

They can not keep renewing the key.
Anyone who want's to issue a cert for the domain, he must verify his ownership of the domain.  Otherwise they can not issue cert for the specified domain.

The domain key is just a few numbers in it.   for example: the rsa key contains `m` and `e` 2 numbers,   and the EC key contains `x` and `y` 2 numbers.

That's why you can use the same private key for multiple times.  they are just numbers.


For MITM,  that's another big topic.   There are 2 major key exchange method in the ssl handshake:  RSA and DH(including DHE,  ECDH and ECDHE) serial methods.

For the RSA kex method,  the symmetric  encryption key is encrypted by the RSA key in the cert, so, if the private key is compromised,    the hacker can decrypt the  symmetric  encryption key by the private key,  then he can decrypt the traffic by the  symmetric  key. 

However, For the DH serial kex method,  the cert key is only used to sign the ssh handshake messages.  So, if the private key is compromised, the hacker can not decrypt the symetric key.   the previous traffic is safe.

For both the RSA and DH kex method,  if the private is compromised, there is no way to protect from MITM for future traffic,  unless you revoke the compromised cert in time.


Fortunately, most of the ssl/tls implementations prefer  DH rather than RSA kex method. 

BTW, the RSA kex method can only use a RSA cert,  but the DH(including  ECDH) serials can use either RSA cert or a ECC cert.

**Comment by FernandoMiguel** [comment]
right, i was aware DH would be impossible.
i was referring to RSA.

thanks for clarifying

**Comment by chinkung** [comment]
One thing I notice is there are a lot of certificate records in CT logs when I try to issue it multiple times http://crt.sh

**Comment by Neilpang** [comment]
@chinkung 
Yes,  every cert has a record there.
